kind: Pod
apiVersion: v1
metadata:
  generateName: blog-django-py-git-db8cd5c56-
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.128.24.106"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "interface": "eth0",
          "ips": [
              "10.128.24.106"
          ],
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container
      blog-django-py-git; cpu, memory limit for container blog-django-py-git
    openshift.io/scc: restricted
  selfLink: /api/v1/namespaces/rm343718-final/pods/blog-django-py-git-db8cd5c56-mjqgp
  resourceVersion: '97277741'
  name: blog-django-py-git-db8cd5c56-mjqgp
  uid: 9f05f7c8-f248-49a9-b139-7f413a78dc40
  creationTimestamp: '2022-07-14T03:31:11Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-07-14T03:31:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deploymentconfig': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"08bd5ec2-179e-4920-9bcf-85737a2d9614"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"blog-django-py-git"}':
              'f:image': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:env':
                .: {}
                'k:{"name":"BLOG_BANNER_COLOR"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"BLOG_SITE_NAME"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"DATABASE_URL"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8080,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2022-07-14T03:31:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-07-14T03:31:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.128.24.106"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
  namespace: rm343718-final
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: blog-django-py-git-db8cd5c56
      uid: 08bd5ec2-179e-4920-9bcf-85737a2d9614
      controller: true
      blockOwnerDeletion: true
  labels:
    app: blog-django-py-git
    deploymentconfig: blog-django-py-git
    pod-template-hash: db8cd5c56
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-2szp2
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: ip-10-0-182-176.us-east-2.compute.internal
  securityContext:
    seLinuxOptions:
      level: 's0:c50,c25'
    fsGroup: 1002500000
  containers:
    - resources:
        limits:
          cpu: 1500m
          memory: 2Gi
        requests:
          cpu: 5m
          memory: 50Mi
      terminationMessagePath: /dev/termination-log
      name: blog-django-py-git
      env:
        - name: DATABASE_URL
          value: 'postgresql://sampledb:sampledb@sample-database:5432/sampledb'
        - name: BLOG_SITE_NAME
          value: '''RM-343718'''
        - name: BLOG_BANNER_COLOR
          value: blue
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1002500000
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: default-token-dxjn4
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/rm343718-final/blog-django-py-git@sha256:62106e19bfe28ad89d516469cd3d2ff6ef1153c3d6ddccd1e76d7ce66f742b55
  serviceAccount: default
  volumes:
    - name: default-token-dxjn4
      secret:
        secretName: default-token-dxjn4
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-14T03:31:11Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-14T03:31:15Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-14T03:31:15Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-07-14T03:31:11Z'
  hostIP: 10.0.182.176
  podIP: 10.128.24.106
  podIPs:
    - ip: 10.128.24.106
  startTime: '2022-07-14T03:31:11Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: blog-django-py-git
      state:
        running:
          startedAt: '2022-07-14T03:31:14Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/rm343718-final/blog-django-py-git@sha256:62106e19bfe28ad89d516469cd3d2ff6ef1153c3d6ddccd1e76d7ce66f742b55
      image: >-
        image-registry.openshift-image-registry.svc:5000/rm343718-final/blog-django-py-git@sha256:62106e19bfe28ad89d516469cd3d2ff6ef1153c3d6ddccd1e76d7ce66f742b55
      lastState: {}
      containerID: 'cri-o://3d9f2fed820522dcdb953ccb5b25f675d266a2641f1c890d120cb2ca6ee3238b'
  qosClass: Burstable
